# Pre-commit Configuration for Inscribe Data Processing Service
# This configuration runs the same checks as the CircleCI pipeline

repos:
  # Code formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100]
        files: ^(src/|tests/).*\.py$

  # Import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile, black, --line-length=100]
        files: ^(src/|tests/).*\.py$

  # Linting with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [--max-line-length=100, "--extend-ignore=E203,W503"]
        files: ^(src/|tests/).*\.py$

  # Unit tests with pytest
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        args: [tests/, -v, --tb=short, --cov=src/app, --cov-report=term]
        files: ^(src/|tests/).*\.py$
        pass_filenames: false

# Optional hooks that can be enabled by uncommenting:
# 
# Security scanning with bandit:
# - repo: https://github.com/pycqa/bandit
#   rev: 1.7.9
#   hooks:
#     - id: bandit
#       args: [-r, src/, --skip, B107,B608]  # Skip hardcoded password and SQL injection warnings
#       files: ^src/.*\.py$
#
# Type checking with mypy (disabled due to Pydantic v2 compatibility issues):
# - repo: local
#   hooks:
#     - id: mypy
#       name: mypy
#       entry: mypy
#       language: system
#       args: [src/app/, --ignore-missing-imports, --no-strict-optional, --allow-untyped-calls]
#       files: ^src/.*\.py$
#       pass_filenames: false
