version: 2.1

orbs:
  docker: circleci/docker@3.0.0
  aws-cli: circleci/aws-cli@5.4.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.13
    working_directory: ~/repo
    environment:
      PYTHONPATH: /home/circleci/repo/src

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}
            - v1-dependencies-
      
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r test-requirements.txt
      
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}
      
      - run:
          name: Run linting
          command: |
            . venv/bin/activate
            pip install flake8==7.1.1 black==24.8.0 isort==5.13.2 mypy==1.11.2
            echo "Running Black formatter check..."
            black --check src/ tests/ || (echo "Code formatting issues found. Run 'black src/ tests/' to fix." && exit 1)
            echo "Running isort import sorting check..."
            isort --profile black --check-only src/ tests/ || (echo "Import sorting issues found. Run 'isort src/ tests/' to fix." && exit 1)
            echo "Running flake8 linting..."
            flake8 src/ tests/ --max-line-length=100 --extend-ignore=E203,W503
            echo "Running mypy type checking..."
            mypy src/app/ --ignore-missing-imports || true
      
      - run:
          name: Run unit tests with coverage
          command: |
            . venv/bin/activate
            pip install pytest-cov==5.0.0 pytest-html==4.1.1
            mkdir -p test-results/junit
            mkdir -p test-results/coverage
            pytest tests/ -v --tb=short \
              --cov=src/app \
              --cov-report=xml:test-results/coverage/coverage.xml \
              --cov-report=html:test-results/coverage/htmlcov \
              --cov-report=term \
              --junit-xml=test-results/junit/pytest.xml \
              --html=test-results/coverage/report.html --self-contained-html
      
      - run:
          name: Run security checks
          command: |
            . venv/bin/activate
            pip install bandit==1.7.9 safety==3.2.7
            echo "Running Bandit security scan..."
            bandit -r src/ -f json -o bandit-report.json || true
            echo "Running Safety dependency vulnerability scan..."
            safety check --json --output safety-report.json || true
            echo "Running pip-audit for known vulnerabilities..."
            pip install pip-audit==2.7.3
            pip-audit --format=json --output=pip-audit-report.json || true
      
      - store_test_results:
          path: test-results/junit
      
      - store_artifacts:
          path: test-results/coverage/
          destination: test-results/coverage/
      
      - store_artifacts:
          path: test-results/junit/
          destination: test-results/junit/
      
      - store_artifacts:
          path: bandit-report.json
          destination: security/bandit-report.json
      
      - store_artifacts:
          path: safety-report.json
          destination: security/safety-report.json
      
      - store_artifacts:
          path: pip-audit-report.json
          destination: security/pip-audit-report.json

  build-and-push:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - aws-cli/setup
      
      - run:
          name: Build Docker image
          command: |
            echo "Building Docker image with tag: inscribe-app:${CIRCLE_SHA1}"
            docker build -t inscribe-app:${CIRCLE_SHA1} .
            docker tag inscribe-app:${CIRCLE_SHA1} inscribe-app:latest
            
            # Test the built image
            echo "Testing Docker image..."
            docker run --rm -d --name test-container \
              -p 8000:8000 \
              -e DB_HOST=localhost \
              -e DB_NAME=test \
              -e DB_USER=test \
              -e DB_PASSWORD=test \
              inscribe-app:${CIRCLE_SHA1} &
            
            # Wait for container to start
            sleep 10
            
            # Basic health check (this will fail due to no DB, but tests image runs)
            docker logs test-container || true
            docker stop test-container || true
      
      - run:
          name: Run container security scan
          command: |
            # Install Trivy for container scanning
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
            echo "Running container security scan..."
            trivy image --exit-code 0 --severity HIGH,CRITICAL \
              --format json --output trivy-report.json \
              inscribe-app:${CIRCLE_SHA1}
            
            # Also generate readable format
            trivy image --severity HIGH,CRITICAL inscribe-app:${CIRCLE_SHA1}
      
      - store_artifacts:
          path: trivy-report.json
          destination: security/trivy-report.json

workflows:
  build-test-deploy:
    jobs:
      - test
      
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only: main
